/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as SettingsProvidersRouteImport } from './routes/settings/providers'
import { Route as SettingsMcpRouteImport } from './routes/settings/mcp'
import { Route as ChatSessionKeyRouteImport } from './routes/chat/$sessionKey'
import { Route as ApiWorkspaceRouteImport } from './routes/api/workspace'
import { Route as ApiTerminalStreamRouteImport } from './routes/api/terminal-stream'
import { Route as ApiTerminalResizeRouteImport } from './routes/api/terminal-resize'
import { Route as ApiTerminalInputRouteImport } from './routes/api/terminal-input'
import { Route as ApiTerminalCloseRouteImport } from './routes/api/terminal-close'
import { Route as ApiStartHermesRouteImport } from './routes/api/start-hermes'
import { Route as ApiStartAgentRouteImport } from './routes/api/start-agent'
import { Route as ApiSkillsRouteImport } from './routes/api/skills'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiSessionStatusRouteImport } from './routes/api/session-status'
import { Route as ApiSendStreamRouteImport } from './routes/api/send-stream'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiPathsRouteImport } from './routes/api/paths'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiMemoryRouteImport } from './routes/api/memory'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiHermesJobsRouteImport } from './routes/api/hermes-jobs'
import { Route as ApiHermesConfigRouteImport } from './routes/api/hermes-config'
import { Route as ApiGatewayStatusRouteImport } from './routes/api/gateway-status'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiContextUsageRouteImport } from './routes/api/context-usage'
import { Route as ApiConnectionStatusRouteImport } from './routes/api/connection-status'
import { Route as ApiChatEventsRouteImport } from './routes/api/chat-events'
import { Route as ApiAuthCheckRouteImport } from './routes/api/auth-check'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiWorkspacesOpenRouteImport } from './routes/api/workspaces/open'
import { Route as ApiWorkspacesListRouteImport } from './routes/api/workspaces/list'
import { Route as ApiWorkspacesCreateRouteImport } from './routes/api/workspaces/create'
import { Route as ApiWorkspacesCloneRouteImport } from './routes/api/workspaces/clone'
import { Route as ApiSylangVariantMatrixRouteImport } from './routes/api/sylang/variant-matrix'
import { Route as ApiSylangSymbolsRouteImport } from './routes/api/sylang/symbols'
import { Route as ApiSylangSymbolDetailsRouteImport } from './routes/api/sylang/symbol-details'
import { Route as ApiSylangDiagramRouteImport } from './routes/api/sylang/diagram'
import { Route as ApiSkillsUninstallRouteImport } from './routes/api/skills/uninstall'
import { Route as ApiSkillsInstallRouteImport } from './routes/api/skills/install'
import { Route as ApiSkillsHubSearchRouteImport } from './routes/api/skills/hub-search'
import { Route as ApiSessionsSendRouteImport } from './routes/api/sessions/send'
import { Route as ApiProfilesRenameRouteImport } from './routes/api/profiles/rename'
import { Route as ApiProfilesReadRouteImport } from './routes/api/profiles/read'
import { Route as ApiProfilesListRouteImport } from './routes/api/profiles/list'
import { Route as ApiProfilesDeleteRouteImport } from './routes/api/profiles/delete'
import { Route as ApiProfilesCreateRouteImport } from './routes/api/profiles/create'
import { Route as ApiProfilesActivateRouteImport } from './routes/api/profiles/activate'
import { Route as ApiOauthPollTokenRouteImport } from './routes/api/oauth.poll-token'
import { Route as ApiOauthDeviceCodeRouteImport } from './routes/api/oauth.device-code'
import { Route as ApiMemoryWriteRouteImport } from './routes/api/memory/write'
import { Route as ApiMemorySearchRouteImport } from './routes/api/memory/search'
import { Route as ApiMemoryReadRouteImport } from './routes/api/memory/read'
import { Route as ApiMemoryListRouteImport } from './routes/api/memory/list'
import { Route as ApiMcpServersRouteImport } from './routes/api/mcp/servers'
import { Route as ApiMcpReloadRouteImport } from './routes/api/mcp/reload'
import { Route as ApiKnowledgeSearchRouteImport } from './routes/api/knowledge/search'
import { Route as ApiKnowledgeReadRouteImport } from './routes/api/knowledge/read'
import { Route as ApiKnowledgeListRouteImport } from './routes/api/knowledge/list'
import { Route as ApiKnowledgeGraphRouteImport } from './routes/api/knowledge/graph'
import { Route as ApiHermesProxySplatRouteImport } from './routes/api/hermes-proxy/$'
import { Route as ApiHermesJobsJobIdRouteImport } from './routes/api/hermes-jobs.$jobId'
import { Route as ApiGithubReposRouteImport } from './routes/api/github/repos'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthGithubRouteImport } from './routes/api/auth/github'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAgentsTestRouteImport } from './routes/api/agents/test'
import { Route as ApiAgentsSelectRouteImport } from './routes/api/agents/select'
import { Route as ApiAgentsListRouteImport } from './routes/api/agents/list'
import { Route as ApiAgentsAddRouteImport } from './routes/api/agents/add'
import { Route as ApiAgentSessionsStatusRouteImport } from './routes/api/agent-sessions/status'
import { Route as ApiAgentSessionsStartRouteImport } from './routes/api/agent-sessions/start'
import { Route as ApiAgentSessionsHealthCheckRouteImport } from './routes/api/agent-sessions/health-check'
import { Route as ApiAgentSessionsEndRouteImport } from './routes/api/agent-sessions/end'
import { Route as ApiSessionsSessionKeyStatusRouteImport } from './routes/api/sessions/$sessionKey.status'
import { Route as ApiSessionsSessionKeyActiveRunRouteImport } from './routes/api/sessions/$sessionKey.active-run'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMcpRoute = SettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatSessionKeyRoute = ChatSessionKeyRouteImport.update({
  id: '/chat/$sessionKey',
  path: '/chat/$sessionKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalStreamRoute = ApiTerminalStreamRouteImport.update({
  id: '/api/terminal-stream',
  path: '/api/terminal-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalResizeRoute = ApiTerminalResizeRouteImport.update({
  id: '/api/terminal-resize',
  path: '/api/terminal-resize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalInputRoute = ApiTerminalInputRouteImport.update({
  id: '/api/terminal-input',
  path: '/api/terminal-input',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalCloseRoute = ApiTerminalCloseRouteImport.update({
  id: '/api/terminal-close',
  path: '/api/terminal-close',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStartHermesRoute = ApiStartHermesRouteImport.update({
  id: '/api/start-hermes',
  path: '/api/start-hermes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStartAgentRoute = ApiStartAgentRouteImport.update({
  id: '/api/start-agent',
  path: '/api/start-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsRoute = ApiSkillsRouteImport.update({
  id: '/api/skills',
  path: '/api/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionStatusRoute = ApiSessionStatusRouteImport.update({
  id: '/api/session-status',
  path: '/api/session-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendStreamRoute = ApiSendStreamRouteImport.update({
  id: '/api/send-stream',
  path: '/api/send-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPathsRoute = ApiPathsRouteImport.update({
  id: '/api/paths',
  path: '/api/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryRoute = ApiMemoryRouteImport.update({
  id: '/api/memory',
  path: '/api/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesJobsRoute = ApiHermesJobsRouteImport.update({
  id: '/api/hermes-jobs',
  path: '/api/hermes-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesConfigRoute = ApiHermesConfigRouteImport.update({
  id: '/api/hermes-config',
  path: '/api/hermes-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewayStatusRoute = ApiGatewayStatusRouteImport.update({
  id: '/api/gateway-status',
  path: '/api/gateway-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContextUsageRoute = ApiContextUsageRouteImport.update({
  id: '/api/context-usage',
  path: '/api/context-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionStatusRoute = ApiConnectionStatusRouteImport.update({
  id: '/api/connection-status',
  path: '/api/connection-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatEventsRoute = ApiChatEventsRouteImport.update({
  id: '/api/chat-events',
  path: '/api/chat-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCheckRoute = ApiAuthCheckRouteImport.update({
  id: '/api/auth-check',
  path: '/api/auth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspacesOpenRoute = ApiWorkspacesOpenRouteImport.update({
  id: '/api/workspaces/open',
  path: '/api/workspaces/open',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspacesListRoute = ApiWorkspacesListRouteImport.update({
  id: '/api/workspaces/list',
  path: '/api/workspaces/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspacesCreateRoute = ApiWorkspacesCreateRouteImport.update({
  id: '/api/workspaces/create',
  path: '/api/workspaces/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspacesCloneRoute = ApiWorkspacesCloneRouteImport.update({
  id: '/api/workspaces/clone',
  path: '/api/workspaces/clone',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSylangVariantMatrixRoute = ApiSylangVariantMatrixRouteImport.update({
  id: '/api/sylang/variant-matrix',
  path: '/api/sylang/variant-matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSylangSymbolsRoute = ApiSylangSymbolsRouteImport.update({
  id: '/api/sylang/symbols',
  path: '/api/sylang/symbols',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSylangSymbolDetailsRoute = ApiSylangSymbolDetailsRouteImport.update({
  id: '/api/sylang/symbol-details',
  path: '/api/sylang/symbol-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSylangDiagramRoute = ApiSylangDiagramRouteImport.update({
  id: '/api/sylang/diagram',
  path: '/api/sylang/diagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsUninstallRoute = ApiSkillsUninstallRouteImport.update({
  id: '/uninstall',
  path: '/uninstall',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSkillsInstallRoute = ApiSkillsInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSkillsHubSearchRoute = ApiSkillsHubSearchRouteImport.update({
  id: '/hub-search',
  path: '/hub-search',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSessionsSendRoute = ApiSessionsSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => ApiSessionsRoute,
} as any)
const ApiProfilesRenameRoute = ApiProfilesRenameRouteImport.update({
  id: '/api/profiles/rename',
  path: '/api/profiles/rename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesReadRoute = ApiProfilesReadRouteImport.update({
  id: '/api/profiles/read',
  path: '/api/profiles/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesListRoute = ApiProfilesListRouteImport.update({
  id: '/api/profiles/list',
  path: '/api/profiles/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesDeleteRoute = ApiProfilesDeleteRouteImport.update({
  id: '/api/profiles/delete',
  path: '/api/profiles/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesCreateRoute = ApiProfilesCreateRouteImport.update({
  id: '/api/profiles/create',
  path: '/api/profiles/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesActivateRoute = ApiProfilesActivateRouteImport.update({
  id: '/api/profiles/activate',
  path: '/api/profiles/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthPollTokenRoute = ApiOauthPollTokenRouteImport.update({
  id: '/api/oauth/poll-token',
  path: '/api/oauth/poll-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthDeviceCodeRoute = ApiOauthDeviceCodeRouteImport.update({
  id: '/api/oauth/device-code',
  path: '/api/oauth/device-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryWriteRoute = ApiMemoryWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => ApiMemoryRoute,
} as any)
const ApiMemorySearchRoute = ApiMemorySearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiMemoryRoute,
} as any)
const ApiMemoryReadRoute = ApiMemoryReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => ApiMemoryRoute,
} as any)
const ApiMemoryListRoute = ApiMemoryListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => ApiMemoryRoute,
} as any)
const ApiMcpServersRoute = ApiMcpServersRouteImport.update({
  id: '/api/mcp/servers',
  path: '/api/mcp/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpReloadRoute = ApiMcpReloadRouteImport.update({
  id: '/api/mcp/reload',
  path: '/api/mcp/reload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeSearchRoute = ApiKnowledgeSearchRouteImport.update({
  id: '/api/knowledge/search',
  path: '/api/knowledge/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeReadRoute = ApiKnowledgeReadRouteImport.update({
  id: '/api/knowledge/read',
  path: '/api/knowledge/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeListRoute = ApiKnowledgeListRouteImport.update({
  id: '/api/knowledge/list',
  path: '/api/knowledge/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeGraphRoute = ApiKnowledgeGraphRouteImport.update({
  id: '/api/knowledge/graph',
  path: '/api/knowledge/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesProxySplatRoute = ApiHermesProxySplatRouteImport.update({
  id: '/api/hermes-proxy/$',
  path: '/api/hermes-proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesJobsJobIdRoute = ApiHermesJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiHermesJobsRoute,
} as any)
const ApiGithubReposRoute = ApiGithubReposRouteImport.update({
  id: '/api/github/repos',
  path: '/api/github/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => ApiAuthRoute,
} as any)
const ApiAuthGithubRoute = ApiAuthGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => ApiAuthRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthRoute,
} as any)
const ApiAgentsTestRoute = ApiAgentsTestRouteImport.update({
  id: '/api/agents/test',
  path: '/api/agents/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsSelectRoute = ApiAgentsSelectRouteImport.update({
  id: '/api/agents/select',
  path: '/api/agents/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsListRoute = ApiAgentsListRouteImport.update({
  id: '/api/agents/list',
  path: '/api/agents/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsAddRoute = ApiAgentsAddRouteImport.update({
  id: '/api/agents/add',
  path: '/api/agents/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentSessionsStatusRoute = ApiAgentSessionsStatusRouteImport.update({
  id: '/api/agent-sessions/status',
  path: '/api/agent-sessions/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentSessionsStartRoute = ApiAgentSessionsStartRouteImport.update({
  id: '/api/agent-sessions/start',
  path: '/api/agent-sessions/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentSessionsHealthCheckRoute =
  ApiAgentSessionsHealthCheckRouteImport.update({
    id: '/api/agent-sessions/health-check',
    path: '/api/agent-sessions/health-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentSessionsEndRoute = ApiAgentSessionsEndRouteImport.update({
  id: '/api/agent-sessions/end',
  path: '/api/agent-sessions/end',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsSessionKeyStatusRoute =
  ApiSessionsSessionKeyStatusRouteImport.update({
    id: '/$sessionKey/status',
    path: '/$sessionKey/status',
    getParentRoute: () => ApiSessionsRoute,
  } as any)
const ApiSessionsSessionKeyActiveRunRoute =
  ApiSessionsSessionKeyActiveRunRouteImport.update({
    id: '/$sessionKey/active-run',
    path: '/$sessionKey/active-run',
    getParentRoute: () => ApiSessionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/agents': typeof AgentsRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/memory': typeof MemoryRoute
  '/profiles': typeof ProfilesRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/terminal': typeof TerminalRoute
  '/terms': typeof TermsRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/connection-status': typeof ApiConnectionStatusRoute
  '/api/context-usage': typeof ApiContextUsageRoute
  '/api/events': typeof ApiEventsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/gateway-status': typeof ApiGatewayStatusRoute
  '/api/hermes-config': typeof ApiHermesConfigRoute
  '/api/hermes-jobs': typeof ApiHermesJobsRouteWithChildren
  '/api/history': typeof ApiHistoryRoute
  '/api/memory': typeof ApiMemoryRouteWithChildren
  '/api/models': typeof ApiModelsRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/send-stream': typeof ApiSendStreamRoute
  '/api/session-status': typeof ApiSessionStatusRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/start-agent': typeof ApiStartAgentRoute
  '/api/start-hermes': typeof ApiStartHermesRoute
  '/api/terminal-close': typeof ApiTerminalCloseRoute
  '/api/terminal-input': typeof ApiTerminalInputRoute
  '/api/terminal-resize': typeof ApiTerminalResizeRoute
  '/api/terminal-stream': typeof ApiTerminalStreamRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/agent-sessions/end': typeof ApiAgentSessionsEndRoute
  '/api/agent-sessions/health-check': typeof ApiAgentSessionsHealthCheckRoute
  '/api/agent-sessions/start': typeof ApiAgentSessionsStartRoute
  '/api/agent-sessions/status': typeof ApiAgentSessionsStatusRoute
  '/api/agents/add': typeof ApiAgentsAddRoute
  '/api/agents/list': typeof ApiAgentsListRoute
  '/api/agents/select': typeof ApiAgentsSelectRoute
  '/api/agents/test': typeof ApiAgentsTestRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/hermes-jobs/$jobId': typeof ApiHermesJobsJobIdRoute
  '/api/hermes-proxy/$': typeof ApiHermesProxySplatRoute
  '/api/knowledge/graph': typeof ApiKnowledgeGraphRoute
  '/api/knowledge/list': typeof ApiKnowledgeListRoute
  '/api/knowledge/read': typeof ApiKnowledgeReadRoute
  '/api/knowledge/search': typeof ApiKnowledgeSearchRoute
  '/api/mcp/reload': typeof ApiMcpReloadRoute
  '/api/mcp/servers': typeof ApiMcpServersRoute
  '/api/memory/list': typeof ApiMemoryListRoute
  '/api/memory/read': typeof ApiMemoryReadRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/write': typeof ApiMemoryWriteRoute
  '/api/oauth/device-code': typeof ApiOauthDeviceCodeRoute
  '/api/oauth/poll-token': typeof ApiOauthPollTokenRoute
  '/api/profiles/activate': typeof ApiProfilesActivateRoute
  '/api/profiles/create': typeof ApiProfilesCreateRoute
  '/api/profiles/delete': typeof ApiProfilesDeleteRoute
  '/api/profiles/list': typeof ApiProfilesListRoute
  '/api/profiles/read': typeof ApiProfilesReadRoute
  '/api/profiles/rename': typeof ApiProfilesRenameRoute
  '/api/sessions/send': typeof ApiSessionsSendRoute
  '/api/skills/hub-search': typeof ApiSkillsHubSearchRoute
  '/api/skills/install': typeof ApiSkillsInstallRoute
  '/api/skills/uninstall': typeof ApiSkillsUninstallRoute
  '/api/sylang/diagram': typeof ApiSylangDiagramRoute
  '/api/sylang/symbol-details': typeof ApiSylangSymbolDetailsRoute
  '/api/sylang/symbols': typeof ApiSylangSymbolsRoute
  '/api/sylang/variant-matrix': typeof ApiSylangVariantMatrixRoute
  '/api/workspaces/clone': typeof ApiWorkspacesCloneRoute
  '/api/workspaces/create': typeof ApiWorkspacesCreateRoute
  '/api/workspaces/list': typeof ApiWorkspacesListRoute
  '/api/workspaces/open': typeof ApiWorkspacesOpenRoute
  '/api/sessions/$sessionKey/active-run': typeof ApiSessionsSessionKeyActiveRunRoute
  '/api/sessions/$sessionKey/status': typeof ApiSessionsSessionKeyStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/agents': typeof AgentsRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/memory': typeof MemoryRoute
  '/profiles': typeof ProfilesRoute
  '/projects': typeof ProjectsRoute
  '/skills': typeof SkillsRoute
  '/terminal': typeof TerminalRoute
  '/terms': typeof TermsRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/connection-status': typeof ApiConnectionStatusRoute
  '/api/context-usage': typeof ApiContextUsageRoute
  '/api/events': typeof ApiEventsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/gateway-status': typeof ApiGatewayStatusRoute
  '/api/hermes-config': typeof ApiHermesConfigRoute
  '/api/hermes-jobs': typeof ApiHermesJobsRouteWithChildren
  '/api/history': typeof ApiHistoryRoute
  '/api/memory': typeof ApiMemoryRouteWithChildren
  '/api/models': typeof ApiModelsRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/send-stream': typeof ApiSendStreamRoute
  '/api/session-status': typeof ApiSessionStatusRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/start-agent': typeof ApiStartAgentRoute
  '/api/start-hermes': typeof ApiStartHermesRoute
  '/api/terminal-close': typeof ApiTerminalCloseRoute
  '/api/terminal-input': typeof ApiTerminalInputRoute
  '/api/terminal-resize': typeof ApiTerminalResizeRoute
  '/api/terminal-stream': typeof ApiTerminalStreamRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/chat': typeof ChatIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/agent-sessions/end': typeof ApiAgentSessionsEndRoute
  '/api/agent-sessions/health-check': typeof ApiAgentSessionsHealthCheckRoute
  '/api/agent-sessions/start': typeof ApiAgentSessionsStartRoute
  '/api/agent-sessions/status': typeof ApiAgentSessionsStatusRoute
  '/api/agents/add': typeof ApiAgentsAddRoute
  '/api/agents/list': typeof ApiAgentsListRoute
  '/api/agents/select': typeof ApiAgentsSelectRoute
  '/api/agents/test': typeof ApiAgentsTestRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/hermes-jobs/$jobId': typeof ApiHermesJobsJobIdRoute
  '/api/hermes-proxy/$': typeof ApiHermesProxySplatRoute
  '/api/knowledge/graph': typeof ApiKnowledgeGraphRoute
  '/api/knowledge/list': typeof ApiKnowledgeListRoute
  '/api/knowledge/read': typeof ApiKnowledgeReadRoute
  '/api/knowledge/search': typeof ApiKnowledgeSearchRoute
  '/api/mcp/reload': typeof ApiMcpReloadRoute
  '/api/mcp/servers': typeof ApiMcpServersRoute
  '/api/memory/list': typeof ApiMemoryListRoute
  '/api/memory/read': typeof ApiMemoryReadRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/write': typeof ApiMemoryWriteRoute
  '/api/oauth/device-code': typeof ApiOauthDeviceCodeRoute
  '/api/oauth/poll-token': typeof ApiOauthPollTokenRoute
  '/api/profiles/activate': typeof ApiProfilesActivateRoute
  '/api/profiles/create': typeof ApiProfilesCreateRoute
  '/api/profiles/delete': typeof ApiProfilesDeleteRoute
  '/api/profiles/list': typeof ApiProfilesListRoute
  '/api/profiles/read': typeof ApiProfilesReadRoute
  '/api/profiles/rename': typeof ApiProfilesRenameRoute
  '/api/sessions/send': typeof ApiSessionsSendRoute
  '/api/skills/hub-search': typeof ApiSkillsHubSearchRoute
  '/api/skills/install': typeof ApiSkillsInstallRoute
  '/api/skills/uninstall': typeof ApiSkillsUninstallRoute
  '/api/sylang/diagram': typeof ApiSylangDiagramRoute
  '/api/sylang/symbol-details': typeof ApiSylangSymbolDetailsRoute
  '/api/sylang/symbols': typeof ApiSylangSymbolsRoute
  '/api/sylang/variant-matrix': typeof ApiSylangVariantMatrixRoute
  '/api/workspaces/clone': typeof ApiWorkspacesCloneRoute
  '/api/workspaces/create': typeof ApiWorkspacesCreateRoute
  '/api/workspaces/list': typeof ApiWorkspacesListRoute
  '/api/workspaces/open': typeof ApiWorkspacesOpenRoute
  '/api/sessions/$sessionKey/active-run': typeof ApiSessionsSessionKeyActiveRunRoute
  '/api/sessions/$sessionKey/status': typeof ApiSessionsSessionKeyStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/agents': typeof AgentsRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/memory': typeof MemoryRoute
  '/profiles': typeof ProfilesRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/terminal': typeof TerminalRoute
  '/terms': typeof TermsRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/connection-status': typeof ApiConnectionStatusRoute
  '/api/context-usage': typeof ApiContextUsageRoute
  '/api/events': typeof ApiEventsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/gateway-status': typeof ApiGatewayStatusRoute
  '/api/hermes-config': typeof ApiHermesConfigRoute
  '/api/hermes-jobs': typeof ApiHermesJobsRouteWithChildren
  '/api/history': typeof ApiHistoryRoute
  '/api/memory': typeof ApiMemoryRouteWithChildren
  '/api/models': typeof ApiModelsRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/send-stream': typeof ApiSendStreamRoute
  '/api/session-status': typeof ApiSessionStatusRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/start-agent': typeof ApiStartAgentRoute
  '/api/start-hermes': typeof ApiStartHermesRoute
  '/api/terminal-close': typeof ApiTerminalCloseRoute
  '/api/terminal-input': typeof ApiTerminalInputRoute
  '/api/terminal-resize': typeof ApiTerminalResizeRoute
  '/api/terminal-stream': typeof ApiTerminalStreamRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/agent-sessions/end': typeof ApiAgentSessionsEndRoute
  '/api/agent-sessions/health-check': typeof ApiAgentSessionsHealthCheckRoute
  '/api/agent-sessions/start': typeof ApiAgentSessionsStartRoute
  '/api/agent-sessions/status': typeof ApiAgentSessionsStatusRoute
  '/api/agents/add': typeof ApiAgentsAddRoute
  '/api/agents/list': typeof ApiAgentsListRoute
  '/api/agents/select': typeof ApiAgentsSelectRoute
  '/api/agents/test': typeof ApiAgentsTestRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/hermes-jobs/$jobId': typeof ApiHermesJobsJobIdRoute
  '/api/hermes-proxy/$': typeof ApiHermesProxySplatRoute
  '/api/knowledge/graph': typeof ApiKnowledgeGraphRoute
  '/api/knowledge/list': typeof ApiKnowledgeListRoute
  '/api/knowledge/read': typeof ApiKnowledgeReadRoute
  '/api/knowledge/search': typeof ApiKnowledgeSearchRoute
  '/api/mcp/reload': typeof ApiMcpReloadRoute
  '/api/mcp/servers': typeof ApiMcpServersRoute
  '/api/memory/list': typeof ApiMemoryListRoute
  '/api/memory/read': typeof ApiMemoryReadRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/write': typeof ApiMemoryWriteRoute
  '/api/oauth/device-code': typeof ApiOauthDeviceCodeRoute
  '/api/oauth/poll-token': typeof ApiOauthPollTokenRoute
  '/api/profiles/activate': typeof ApiProfilesActivateRoute
  '/api/profiles/create': typeof ApiProfilesCreateRoute
  '/api/profiles/delete': typeof ApiProfilesDeleteRoute
  '/api/profiles/list': typeof ApiProfilesListRoute
  '/api/profiles/read': typeof ApiProfilesReadRoute
  '/api/profiles/rename': typeof ApiProfilesRenameRoute
  '/api/sessions/send': typeof ApiSessionsSendRoute
  '/api/skills/hub-search': typeof ApiSkillsHubSearchRoute
  '/api/skills/install': typeof ApiSkillsInstallRoute
  '/api/skills/uninstall': typeof ApiSkillsUninstallRoute
  '/api/sylang/diagram': typeof ApiSylangDiagramRoute
  '/api/sylang/symbol-details': typeof ApiSylangSymbolDetailsRoute
  '/api/sylang/symbols': typeof ApiSylangSymbolsRoute
  '/api/sylang/variant-matrix': typeof ApiSylangVariantMatrixRoute
  '/api/workspaces/clone': typeof ApiWorkspacesCloneRoute
  '/api/workspaces/create': typeof ApiWorkspacesCreateRoute
  '/api/workspaces/list': typeof ApiWorkspacesListRoute
  '/api/workspaces/open': typeof ApiWorkspacesOpenRoute
  '/api/sessions/$sessionKey/active-run': typeof ApiSessionsSessionKeyActiveRunRoute
  '/api/sessions/$sessionKey/status': typeof ApiSessionsSessionKeyStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/agents'
    | '/dashboard'
    | '/files'
    | '/jobs'
    | '/memory'
    | '/profiles'
    | '/projects'
    | '/settings'
    | '/skills'
    | '/terminal'
    | '/terms'
    | '/api/auth'
    | '/api/auth-check'
    | '/api/chat-events'
    | '/api/connection-status'
    | '/api/context-usage'
    | '/api/events'
    | '/api/files'
    | '/api/gateway-status'
    | '/api/hermes-config'
    | '/api/hermes-jobs'
    | '/api/history'
    | '/api/memory'
    | '/api/models'
    | '/api/paths'
    | '/api/ping'
    | '/api/send'
    | '/api/send-stream'
    | '/api/session-status'
    | '/api/sessions'
    | '/api/skills'
    | '/api/start-agent'
    | '/api/start-hermes'
    | '/api/terminal-close'
    | '/api/terminal-input'
    | '/api/terminal-resize'
    | '/api/terminal-stream'
    | '/api/workspace'
    | '/chat/$sessionKey'
    | '/settings/mcp'
    | '/settings/providers'
    | '/chat/'
    | '/settings/'
    | '/api/agent-sessions/end'
    | '/api/agent-sessions/health-check'
    | '/api/agent-sessions/start'
    | '/api/agent-sessions/status'
    | '/api/agents/add'
    | '/api/agents/list'
    | '/api/agents/select'
    | '/api/agents/test'
    | '/api/auth/callback'
    | '/api/auth/github'
    | '/api/auth/logout'
    | '/api/github/repos'
    | '/api/hermes-jobs/$jobId'
    | '/api/hermes-proxy/$'
    | '/api/knowledge/graph'
    | '/api/knowledge/list'
    | '/api/knowledge/read'
    | '/api/knowledge/search'
    | '/api/mcp/reload'
    | '/api/mcp/servers'
    | '/api/memory/list'
    | '/api/memory/read'
    | '/api/memory/search'
    | '/api/memory/write'
    | '/api/oauth/device-code'
    | '/api/oauth/poll-token'
    | '/api/profiles/activate'
    | '/api/profiles/create'
    | '/api/profiles/delete'
    | '/api/profiles/list'
    | '/api/profiles/read'
    | '/api/profiles/rename'
    | '/api/sessions/send'
    | '/api/skills/hub-search'
    | '/api/skills/install'
    | '/api/skills/uninstall'
    | '/api/sylang/diagram'
    | '/api/sylang/symbol-details'
    | '/api/sylang/symbols'
    | '/api/sylang/variant-matrix'
    | '/api/workspaces/clone'
    | '/api/workspaces/create'
    | '/api/workspaces/list'
    | '/api/workspaces/open'
    | '/api/sessions/$sessionKey/active-run'
    | '/api/sessions/$sessionKey/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/agents'
    | '/dashboard'
    | '/files'
    | '/jobs'
    | '/memory'
    | '/profiles'
    | '/projects'
    | '/skills'
    | '/terminal'
    | '/terms'
    | '/api/auth'
    | '/api/auth-check'
    | '/api/chat-events'
    | '/api/connection-status'
    | '/api/context-usage'
    | '/api/events'
    | '/api/files'
    | '/api/gateway-status'
    | '/api/hermes-config'
    | '/api/hermes-jobs'
    | '/api/history'
    | '/api/memory'
    | '/api/models'
    | '/api/paths'
    | '/api/ping'
    | '/api/send'
    | '/api/send-stream'
    | '/api/session-status'
    | '/api/sessions'
    | '/api/skills'
    | '/api/start-agent'
    | '/api/start-hermes'
    | '/api/terminal-close'
    | '/api/terminal-input'
    | '/api/terminal-resize'
    | '/api/terminal-stream'
    | '/api/workspace'
    | '/chat/$sessionKey'
    | '/settings/mcp'
    | '/settings/providers'
    | '/chat'
    | '/settings'
    | '/api/agent-sessions/end'
    | '/api/agent-sessions/health-check'
    | '/api/agent-sessions/start'
    | '/api/agent-sessions/status'
    | '/api/agents/add'
    | '/api/agents/list'
    | '/api/agents/select'
    | '/api/agents/test'
    | '/api/auth/callback'
    | '/api/auth/github'
    | '/api/auth/logout'
    | '/api/github/repos'
    | '/api/hermes-jobs/$jobId'
    | '/api/hermes-proxy/$'
    | '/api/knowledge/graph'
    | '/api/knowledge/list'
    | '/api/knowledge/read'
    | '/api/knowledge/search'
    | '/api/mcp/reload'
    | '/api/mcp/servers'
    | '/api/memory/list'
    | '/api/memory/read'
    | '/api/memory/search'
    | '/api/memory/write'
    | '/api/oauth/device-code'
    | '/api/oauth/poll-token'
    | '/api/profiles/activate'
    | '/api/profiles/create'
    | '/api/profiles/delete'
    | '/api/profiles/list'
    | '/api/profiles/read'
    | '/api/profiles/rename'
    | '/api/sessions/send'
    | '/api/skills/hub-search'
    | '/api/skills/install'
    | '/api/skills/uninstall'
    | '/api/sylang/diagram'
    | '/api/sylang/symbol-details'
    | '/api/sylang/symbols'
    | '/api/sylang/variant-matrix'
    | '/api/workspaces/clone'
    | '/api/workspaces/create'
    | '/api/workspaces/list'
    | '/api/workspaces/open'
    | '/api/sessions/$sessionKey/active-run'
    | '/api/sessions/$sessionKey/status'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/agents'
    | '/dashboard'
    | '/files'
    | '/jobs'
    | '/memory'
    | '/profiles'
    | '/projects'
    | '/settings'
    | '/skills'
    | '/terminal'
    | '/terms'
    | '/api/auth'
    | '/api/auth-check'
    | '/api/chat-events'
    | '/api/connection-status'
    | '/api/context-usage'
    | '/api/events'
    | '/api/files'
    | '/api/gateway-status'
    | '/api/hermes-config'
    | '/api/hermes-jobs'
    | '/api/history'
    | '/api/memory'
    | '/api/models'
    | '/api/paths'
    | '/api/ping'
    | '/api/send'
    | '/api/send-stream'
    | '/api/session-status'
    | '/api/sessions'
    | '/api/skills'
    | '/api/start-agent'
    | '/api/start-hermes'
    | '/api/terminal-close'
    | '/api/terminal-input'
    | '/api/terminal-resize'
    | '/api/terminal-stream'
    | '/api/workspace'
    | '/chat/$sessionKey'
    | '/settings/mcp'
    | '/settings/providers'
    | '/chat/'
    | '/settings/'
    | '/api/agent-sessions/end'
    | '/api/agent-sessions/health-check'
    | '/api/agent-sessions/start'
    | '/api/agent-sessions/status'
    | '/api/agents/add'
    | '/api/agents/list'
    | '/api/agents/select'
    | '/api/agents/test'
    | '/api/auth/callback'
    | '/api/auth/github'
    | '/api/auth/logout'
    | '/api/github/repos'
    | '/api/hermes-jobs/$jobId'
    | '/api/hermes-proxy/$'
    | '/api/knowledge/graph'
    | '/api/knowledge/list'
    | '/api/knowledge/read'
    | '/api/knowledge/search'
    | '/api/mcp/reload'
    | '/api/mcp/servers'
    | '/api/memory/list'
    | '/api/memory/read'
    | '/api/memory/search'
    | '/api/memory/write'
    | '/api/oauth/device-code'
    | '/api/oauth/poll-token'
    | '/api/profiles/activate'
    | '/api/profiles/create'
    | '/api/profiles/delete'
    | '/api/profiles/list'
    | '/api/profiles/read'
    | '/api/profiles/rename'
    | '/api/sessions/send'
    | '/api/skills/hub-search'
    | '/api/skills/install'
    | '/api/skills/uninstall'
    | '/api/sylang/diagram'
    | '/api/sylang/symbol-details'
    | '/api/sylang/symbols'
    | '/api/sylang/variant-matrix'
    | '/api/workspaces/clone'
    | '/api/workspaces/create'
    | '/api/workspaces/list'
    | '/api/workspaces/open'
    | '/api/sessions/$sessionKey/active-run'
    | '/api/sessions/$sessionKey/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AgentsRoute: typeof AgentsRoute
  DashboardRoute: typeof DashboardRoute
  FilesRoute: typeof FilesRoute
  JobsRoute: typeof JobsRoute
  MemoryRoute: typeof MemoryRoute
  ProfilesRoute: typeof ProfilesRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SkillsRoute: typeof SkillsRoute
  TerminalRoute: typeof TerminalRoute
  TermsRoute: typeof TermsRoute
  ApiAuthRoute: typeof ApiAuthRouteWithChildren
  ApiAuthCheckRoute: typeof ApiAuthCheckRoute
  ApiChatEventsRoute: typeof ApiChatEventsRoute
  ApiConnectionStatusRoute: typeof ApiConnectionStatusRoute
  ApiContextUsageRoute: typeof ApiContextUsageRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiFilesRoute: typeof ApiFilesRoute
  ApiGatewayStatusRoute: typeof ApiGatewayStatusRoute
  ApiHermesConfigRoute: typeof ApiHermesConfigRoute
  ApiHermesJobsRoute: typeof ApiHermesJobsRouteWithChildren
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiMemoryRoute: typeof ApiMemoryRouteWithChildren
  ApiModelsRoute: typeof ApiModelsRoute
  ApiPathsRoute: typeof ApiPathsRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiSendRoute: typeof ApiSendRoute
  ApiSendStreamRoute: typeof ApiSendStreamRoute
  ApiSessionStatusRoute: typeof ApiSessionStatusRoute
  ApiSessionsRoute: typeof ApiSessionsRouteWithChildren
  ApiSkillsRoute: typeof ApiSkillsRouteWithChildren
  ApiStartAgentRoute: typeof ApiStartAgentRoute
  ApiStartHermesRoute: typeof ApiStartHermesRoute
  ApiTerminalCloseRoute: typeof ApiTerminalCloseRoute
  ApiTerminalInputRoute: typeof ApiTerminalInputRoute
  ApiTerminalResizeRoute: typeof ApiTerminalResizeRoute
  ApiTerminalStreamRoute: typeof ApiTerminalStreamRoute
  ApiWorkspaceRoute: typeof ApiWorkspaceRoute
  ChatSessionKeyRoute: typeof ChatSessionKeyRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ApiAgentSessionsEndRoute: typeof ApiAgentSessionsEndRoute
  ApiAgentSessionsHealthCheckRoute: typeof ApiAgentSessionsHealthCheckRoute
  ApiAgentSessionsStartRoute: typeof ApiAgentSessionsStartRoute
  ApiAgentSessionsStatusRoute: typeof ApiAgentSessionsStatusRoute
  ApiAgentsAddRoute: typeof ApiAgentsAddRoute
  ApiAgentsListRoute: typeof ApiAgentsListRoute
  ApiAgentsSelectRoute: typeof ApiAgentsSelectRoute
  ApiAgentsTestRoute: typeof ApiAgentsTestRoute
  ApiGithubReposRoute: typeof ApiGithubReposRoute
  ApiHermesProxySplatRoute: typeof ApiHermesProxySplatRoute
  ApiKnowledgeGraphRoute: typeof ApiKnowledgeGraphRoute
  ApiKnowledgeListRoute: typeof ApiKnowledgeListRoute
  ApiKnowledgeReadRoute: typeof ApiKnowledgeReadRoute
  ApiKnowledgeSearchRoute: typeof ApiKnowledgeSearchRoute
  ApiMcpReloadRoute: typeof ApiMcpReloadRoute
  ApiMcpServersRoute: typeof ApiMcpServersRoute
  ApiOauthDeviceCodeRoute: typeof ApiOauthDeviceCodeRoute
  ApiOauthPollTokenRoute: typeof ApiOauthPollTokenRoute
  ApiProfilesActivateRoute: typeof ApiProfilesActivateRoute
  ApiProfilesCreateRoute: typeof ApiProfilesCreateRoute
  ApiProfilesDeleteRoute: typeof ApiProfilesDeleteRoute
  ApiProfilesListRoute: typeof ApiProfilesListRoute
  ApiProfilesReadRoute: typeof ApiProfilesReadRoute
  ApiProfilesRenameRoute: typeof ApiProfilesRenameRoute
  ApiSylangDiagramRoute: typeof ApiSylangDiagramRoute
  ApiSylangSymbolDetailsRoute: typeof ApiSylangSymbolDetailsRoute
  ApiSylangSymbolsRoute: typeof ApiSylangSymbolsRoute
  ApiSylangVariantMatrixRoute: typeof ApiSylangVariantMatrixRoute
  ApiWorkspacesCloneRoute: typeof ApiWorkspacesCloneRoute
  ApiWorkspacesCreateRoute: typeof ApiWorkspacesCreateRoute
  ApiWorkspacesListRoute: typeof ApiWorkspacesListRoute
  ApiWorkspacesOpenRoute: typeof ApiWorkspacesOpenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/$sessionKey': {
      id: '/chat/$sessionKey'
      path: '/chat/$sessionKey'
      fullPath: '/chat/$sessionKey'
      preLoaderRoute: typeof ChatSessionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-stream': {
      id: '/api/terminal-stream'
      path: '/api/terminal-stream'
      fullPath: '/api/terminal-stream'
      preLoaderRoute: typeof ApiTerminalStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-resize': {
      id: '/api/terminal-resize'
      path: '/api/terminal-resize'
      fullPath: '/api/terminal-resize'
      preLoaderRoute: typeof ApiTerminalResizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-input': {
      id: '/api/terminal-input'
      path: '/api/terminal-input'
      fullPath: '/api/terminal-input'
      preLoaderRoute: typeof ApiTerminalInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-close': {
      id: '/api/terminal-close'
      path: '/api/terminal-close'
      fullPath: '/api/terminal-close'
      preLoaderRoute: typeof ApiTerminalCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/start-hermes': {
      id: '/api/start-hermes'
      path: '/api/start-hermes'
      fullPath: '/api/start-hermes'
      preLoaderRoute: typeof ApiStartHermesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/start-agent': {
      id: '/api/start-agent'
      path: '/api/start-agent'
      fullPath: '/api/start-agent'
      preLoaderRoute: typeof ApiStartAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills': {
      id: '/api/skills'
      path: '/api/skills'
      fullPath: '/api/skills'
      preLoaderRoute: typeof ApiSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-status': {
      id: '/api/session-status'
      path: '/api/session-status'
      fullPath: '/api/session-status'
      preLoaderRoute: typeof ApiSessionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-stream': {
      id: '/api/send-stream'
      path: '/api/send-stream'
      fullPath: '/api/send-stream'
      preLoaderRoute: typeof ApiSendStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paths': {
      id: '/api/paths'
      path: '/api/paths'
      fullPath: '/api/paths'
      preLoaderRoute: typeof ApiPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory': {
      id: '/api/memory'
      path: '/api/memory'
      fullPath: '/api/memory'
      preLoaderRoute: typeof ApiMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-jobs': {
      id: '/api/hermes-jobs'
      path: '/api/hermes-jobs'
      fullPath: '/api/hermes-jobs'
      preLoaderRoute: typeof ApiHermesJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-config': {
      id: '/api/hermes-config'
      path: '/api/hermes-config'
      fullPath: '/api/hermes-config'
      preLoaderRoute: typeof ApiHermesConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gateway-status': {
      id: '/api/gateway-status'
      path: '/api/gateway-status'
      fullPath: '/api/gateway-status'
      preLoaderRoute: typeof ApiGatewayStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/context-usage': {
      id: '/api/context-usage'
      path: '/api/context-usage'
      fullPath: '/api/context-usage'
      preLoaderRoute: typeof ApiContextUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connection-status': {
      id: '/api/connection-status'
      path: '/api/connection-status'
      fullPath: '/api/connection-status'
      preLoaderRoute: typeof ApiConnectionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-events': {
      id: '/api/chat-events'
      path: '/api/chat-events'
      fullPath: '/api/chat-events'
      preLoaderRoute: typeof ApiChatEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-check': {
      id: '/api/auth-check'
      path: '/api/auth-check'
      fullPath: '/api/auth-check'
      preLoaderRoute: typeof ApiAuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces/open': {
      id: '/api/workspaces/open'
      path: '/api/workspaces/open'
      fullPath: '/api/workspaces/open'
      preLoaderRoute: typeof ApiWorkspacesOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces/list': {
      id: '/api/workspaces/list'
      path: '/api/workspaces/list'
      fullPath: '/api/workspaces/list'
      preLoaderRoute: typeof ApiWorkspacesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces/create': {
      id: '/api/workspaces/create'
      path: '/api/workspaces/create'
      fullPath: '/api/workspaces/create'
      preLoaderRoute: typeof ApiWorkspacesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces/clone': {
      id: '/api/workspaces/clone'
      path: '/api/workspaces/clone'
      fullPath: '/api/workspaces/clone'
      preLoaderRoute: typeof ApiWorkspacesCloneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sylang/variant-matrix': {
      id: '/api/sylang/variant-matrix'
      path: '/api/sylang/variant-matrix'
      fullPath: '/api/sylang/variant-matrix'
      preLoaderRoute: typeof ApiSylangVariantMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sylang/symbols': {
      id: '/api/sylang/symbols'
      path: '/api/sylang/symbols'
      fullPath: '/api/sylang/symbols'
      preLoaderRoute: typeof ApiSylangSymbolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sylang/symbol-details': {
      id: '/api/sylang/symbol-details'
      path: '/api/sylang/symbol-details'
      fullPath: '/api/sylang/symbol-details'
      preLoaderRoute: typeof ApiSylangSymbolDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sylang/diagram': {
      id: '/api/sylang/diagram'
      path: '/api/sylang/diagram'
      fullPath: '/api/sylang/diagram'
      preLoaderRoute: typeof ApiSylangDiagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills/uninstall': {
      id: '/api/skills/uninstall'
      path: '/uninstall'
      fullPath: '/api/skills/uninstall'
      preLoaderRoute: typeof ApiSkillsUninstallRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/skills/install': {
      id: '/api/skills/install'
      path: '/install'
      fullPath: '/api/skills/install'
      preLoaderRoute: typeof ApiSkillsInstallRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/skills/hub-search': {
      id: '/api/skills/hub-search'
      path: '/hub-search'
      fullPath: '/api/skills/hub-search'
      preLoaderRoute: typeof ApiSkillsHubSearchRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/sessions/send': {
      id: '/api/sessions/send'
      path: '/send'
      fullPath: '/api/sessions/send'
      preLoaderRoute: typeof ApiSessionsSendRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
    '/api/profiles/rename': {
      id: '/api/profiles/rename'
      path: '/api/profiles/rename'
      fullPath: '/api/profiles/rename'
      preLoaderRoute: typeof ApiProfilesRenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/read': {
      id: '/api/profiles/read'
      path: '/api/profiles/read'
      fullPath: '/api/profiles/read'
      preLoaderRoute: typeof ApiProfilesReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/list': {
      id: '/api/profiles/list'
      path: '/api/profiles/list'
      fullPath: '/api/profiles/list'
      preLoaderRoute: typeof ApiProfilesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/delete': {
      id: '/api/profiles/delete'
      path: '/api/profiles/delete'
      fullPath: '/api/profiles/delete'
      preLoaderRoute: typeof ApiProfilesDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/create': {
      id: '/api/profiles/create'
      path: '/api/profiles/create'
      fullPath: '/api/profiles/create'
      preLoaderRoute: typeof ApiProfilesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/activate': {
      id: '/api/profiles/activate'
      path: '/api/profiles/activate'
      fullPath: '/api/profiles/activate'
      preLoaderRoute: typeof ApiProfilesActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/poll-token': {
      id: '/api/oauth/poll-token'
      path: '/api/oauth/poll-token'
      fullPath: '/api/oauth/poll-token'
      preLoaderRoute: typeof ApiOauthPollTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/device-code': {
      id: '/api/oauth/device-code'
      path: '/api/oauth/device-code'
      fullPath: '/api/oauth/device-code'
      preLoaderRoute: typeof ApiOauthDeviceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/write': {
      id: '/api/memory/write'
      path: '/write'
      fullPath: '/api/memory/write'
      preLoaderRoute: typeof ApiMemoryWriteRouteImport
      parentRoute: typeof ApiMemoryRoute
    }
    '/api/memory/search': {
      id: '/api/memory/search'
      path: '/search'
      fullPath: '/api/memory/search'
      preLoaderRoute: typeof ApiMemorySearchRouteImport
      parentRoute: typeof ApiMemoryRoute
    }
    '/api/memory/read': {
      id: '/api/memory/read'
      path: '/read'
      fullPath: '/api/memory/read'
      preLoaderRoute: typeof ApiMemoryReadRouteImport
      parentRoute: typeof ApiMemoryRoute
    }
    '/api/memory/list': {
      id: '/api/memory/list'
      path: '/list'
      fullPath: '/api/memory/list'
      preLoaderRoute: typeof ApiMemoryListRouteImport
      parentRoute: typeof ApiMemoryRoute
    }
    '/api/mcp/servers': {
      id: '/api/mcp/servers'
      path: '/api/mcp/servers'
      fullPath: '/api/mcp/servers'
      preLoaderRoute: typeof ApiMcpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/reload': {
      id: '/api/mcp/reload'
      path: '/api/mcp/reload'
      fullPath: '/api/mcp/reload'
      preLoaderRoute: typeof ApiMcpReloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/search': {
      id: '/api/knowledge/search'
      path: '/api/knowledge/search'
      fullPath: '/api/knowledge/search'
      preLoaderRoute: typeof ApiKnowledgeSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/read': {
      id: '/api/knowledge/read'
      path: '/api/knowledge/read'
      fullPath: '/api/knowledge/read'
      preLoaderRoute: typeof ApiKnowledgeReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/list': {
      id: '/api/knowledge/list'
      path: '/api/knowledge/list'
      fullPath: '/api/knowledge/list'
      preLoaderRoute: typeof ApiKnowledgeListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/graph': {
      id: '/api/knowledge/graph'
      path: '/api/knowledge/graph'
      fullPath: '/api/knowledge/graph'
      preLoaderRoute: typeof ApiKnowledgeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-proxy/$': {
      id: '/api/hermes-proxy/$'
      path: '/api/hermes-proxy/$'
      fullPath: '/api/hermes-proxy/$'
      preLoaderRoute: typeof ApiHermesProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-jobs/$jobId': {
      id: '/api/hermes-jobs/$jobId'
      path: '/$jobId'
      fullPath: '/api/hermes-jobs/$jobId'
      preLoaderRoute: typeof ApiHermesJobsJobIdRouteImport
      parentRoute: typeof ApiHermesJobsRoute
    }
    '/api/github/repos': {
      id: '/api/github/repos'
      path: '/api/github/repos'
      fullPath: '/api/github/repos'
      preLoaderRoute: typeof ApiGithubReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof ApiAuthRoute
    }
    '/api/auth/github': {
      id: '/api/auth/github'
      path: '/github'
      fullPath: '/api/auth/github'
      preLoaderRoute: typeof ApiAuthGithubRouteImport
      parentRoute: typeof ApiAuthRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof ApiAuthRoute
    }
    '/api/agents/test': {
      id: '/api/agents/test'
      path: '/api/agents/test'
      fullPath: '/api/agents/test'
      preLoaderRoute: typeof ApiAgentsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/select': {
      id: '/api/agents/select'
      path: '/api/agents/select'
      fullPath: '/api/agents/select'
      preLoaderRoute: typeof ApiAgentsSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/list': {
      id: '/api/agents/list'
      path: '/api/agents/list'
      fullPath: '/api/agents/list'
      preLoaderRoute: typeof ApiAgentsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/add': {
      id: '/api/agents/add'
      path: '/api/agents/add'
      fullPath: '/api/agents/add'
      preLoaderRoute: typeof ApiAgentsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-sessions/status': {
      id: '/api/agent-sessions/status'
      path: '/api/agent-sessions/status'
      fullPath: '/api/agent-sessions/status'
      preLoaderRoute: typeof ApiAgentSessionsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-sessions/start': {
      id: '/api/agent-sessions/start'
      path: '/api/agent-sessions/start'
      fullPath: '/api/agent-sessions/start'
      preLoaderRoute: typeof ApiAgentSessionsStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-sessions/health-check': {
      id: '/api/agent-sessions/health-check'
      path: '/api/agent-sessions/health-check'
      fullPath: '/api/agent-sessions/health-check'
      preLoaderRoute: typeof ApiAgentSessionsHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-sessions/end': {
      id: '/api/agent-sessions/end'
      path: '/api/agent-sessions/end'
      fullPath: '/api/agent-sessions/end'
      preLoaderRoute: typeof ApiAgentSessionsEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$sessionKey/status': {
      id: '/api/sessions/$sessionKey/status'
      path: '/$sessionKey/status'
      fullPath: '/api/sessions/$sessionKey/status'
      preLoaderRoute: typeof ApiSessionsSessionKeyStatusRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
    '/api/sessions/$sessionKey/active-run': {
      id: '/api/sessions/$sessionKey/active-run'
      path: '/$sessionKey/active-run'
      fullPath: '/api/sessions/$sessionKey/active-run'
      preLoaderRoute: typeof ApiSessionsSessionKeyActiveRunRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsMcpRoute: typeof SettingsMcpRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsMcpRoute: SettingsMcpRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ApiAuthRouteChildren {
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthGithubRoute: typeof ApiAuthGithubRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
}

const ApiAuthRouteChildren: ApiAuthRouteChildren = {
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthGithubRoute: ApiAuthGithubRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
}

const ApiAuthRouteWithChildren =
  ApiAuthRoute._addFileChildren(ApiAuthRouteChildren)

interface ApiHermesJobsRouteChildren {
  ApiHermesJobsJobIdRoute: typeof ApiHermesJobsJobIdRoute
}

const ApiHermesJobsRouteChildren: ApiHermesJobsRouteChildren = {
  ApiHermesJobsJobIdRoute: ApiHermesJobsJobIdRoute,
}

const ApiHermesJobsRouteWithChildren = ApiHermesJobsRoute._addFileChildren(
  ApiHermesJobsRouteChildren,
)

interface ApiMemoryRouteChildren {
  ApiMemoryListRoute: typeof ApiMemoryListRoute
  ApiMemoryReadRoute: typeof ApiMemoryReadRoute
  ApiMemorySearchRoute: typeof ApiMemorySearchRoute
  ApiMemoryWriteRoute: typeof ApiMemoryWriteRoute
}

const ApiMemoryRouteChildren: ApiMemoryRouteChildren = {
  ApiMemoryListRoute: ApiMemoryListRoute,
  ApiMemoryReadRoute: ApiMemoryReadRoute,
  ApiMemorySearchRoute: ApiMemorySearchRoute,
  ApiMemoryWriteRoute: ApiMemoryWriteRoute,
}

const ApiMemoryRouteWithChildren = ApiMemoryRoute._addFileChildren(
  ApiMemoryRouteChildren,
)

interface ApiSessionsRouteChildren {
  ApiSessionsSendRoute: typeof ApiSessionsSendRoute
  ApiSessionsSessionKeyActiveRunRoute: typeof ApiSessionsSessionKeyActiveRunRoute
  ApiSessionsSessionKeyStatusRoute: typeof ApiSessionsSessionKeyStatusRoute
}

const ApiSessionsRouteChildren: ApiSessionsRouteChildren = {
  ApiSessionsSendRoute: ApiSessionsSendRoute,
  ApiSessionsSessionKeyActiveRunRoute: ApiSessionsSessionKeyActiveRunRoute,
  ApiSessionsSessionKeyStatusRoute: ApiSessionsSessionKeyStatusRoute,
}

const ApiSessionsRouteWithChildren = ApiSessionsRoute._addFileChildren(
  ApiSessionsRouteChildren,
)

interface ApiSkillsRouteChildren {
  ApiSkillsHubSearchRoute: typeof ApiSkillsHubSearchRoute
  ApiSkillsInstallRoute: typeof ApiSkillsInstallRoute
  ApiSkillsUninstallRoute: typeof ApiSkillsUninstallRoute
}

const ApiSkillsRouteChildren: ApiSkillsRouteChildren = {
  ApiSkillsHubSearchRoute: ApiSkillsHubSearchRoute,
  ApiSkillsInstallRoute: ApiSkillsInstallRoute,
  ApiSkillsUninstallRoute: ApiSkillsUninstallRoute,
}

const ApiSkillsRouteWithChildren = ApiSkillsRoute._addFileChildren(
  ApiSkillsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AgentsRoute: AgentsRoute,
  DashboardRoute: DashboardRoute,
  FilesRoute: FilesRoute,
  JobsRoute: JobsRoute,
  MemoryRoute: MemoryRoute,
  ProfilesRoute: ProfilesRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SkillsRoute: SkillsRoute,
  TerminalRoute: TerminalRoute,
  TermsRoute: TermsRoute,
  ApiAuthRoute: ApiAuthRouteWithChildren,
  ApiAuthCheckRoute: ApiAuthCheckRoute,
  ApiChatEventsRoute: ApiChatEventsRoute,
  ApiConnectionStatusRoute: ApiConnectionStatusRoute,
  ApiContextUsageRoute: ApiContextUsageRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiFilesRoute: ApiFilesRoute,
  ApiGatewayStatusRoute: ApiGatewayStatusRoute,
  ApiHermesConfigRoute: ApiHermesConfigRoute,
  ApiHermesJobsRoute: ApiHermesJobsRouteWithChildren,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiMemoryRoute: ApiMemoryRouteWithChildren,
  ApiModelsRoute: ApiModelsRoute,
  ApiPathsRoute: ApiPathsRoute,
  ApiPingRoute: ApiPingRoute,
  ApiSendRoute: ApiSendRoute,
  ApiSendStreamRoute: ApiSendStreamRoute,
  ApiSessionStatusRoute: ApiSessionStatusRoute,
  ApiSessionsRoute: ApiSessionsRouteWithChildren,
  ApiSkillsRoute: ApiSkillsRouteWithChildren,
  ApiStartAgentRoute: ApiStartAgentRoute,
  ApiStartHermesRoute: ApiStartHermesRoute,
  ApiTerminalCloseRoute: ApiTerminalCloseRoute,
  ApiTerminalInputRoute: ApiTerminalInputRoute,
  ApiTerminalResizeRoute: ApiTerminalResizeRoute,
  ApiTerminalStreamRoute: ApiTerminalStreamRoute,
  ApiWorkspaceRoute: ApiWorkspaceRoute,
  ChatSessionKeyRoute: ChatSessionKeyRoute,
  ChatIndexRoute: ChatIndexRoute,
  ApiAgentSessionsEndRoute: ApiAgentSessionsEndRoute,
  ApiAgentSessionsHealthCheckRoute: ApiAgentSessionsHealthCheckRoute,
  ApiAgentSessionsStartRoute: ApiAgentSessionsStartRoute,
  ApiAgentSessionsStatusRoute: ApiAgentSessionsStatusRoute,
  ApiAgentsAddRoute: ApiAgentsAddRoute,
  ApiAgentsListRoute: ApiAgentsListRoute,
  ApiAgentsSelectRoute: ApiAgentsSelectRoute,
  ApiAgentsTestRoute: ApiAgentsTestRoute,
  ApiGithubReposRoute: ApiGithubReposRoute,
  ApiHermesProxySplatRoute: ApiHermesProxySplatRoute,
  ApiKnowledgeGraphRoute: ApiKnowledgeGraphRoute,
  ApiKnowledgeListRoute: ApiKnowledgeListRoute,
  ApiKnowledgeReadRoute: ApiKnowledgeReadRoute,
  ApiKnowledgeSearchRoute: ApiKnowledgeSearchRoute,
  ApiMcpReloadRoute: ApiMcpReloadRoute,
  ApiMcpServersRoute: ApiMcpServersRoute,
  ApiOauthDeviceCodeRoute: ApiOauthDeviceCodeRoute,
  ApiOauthPollTokenRoute: ApiOauthPollTokenRoute,
  ApiProfilesActivateRoute: ApiProfilesActivateRoute,
  ApiProfilesCreateRoute: ApiProfilesCreateRoute,
  ApiProfilesDeleteRoute: ApiProfilesDeleteRoute,
  ApiProfilesListRoute: ApiProfilesListRoute,
  ApiProfilesReadRoute: ApiProfilesReadRoute,
  ApiProfilesRenameRoute: ApiProfilesRenameRoute,
  ApiSylangDiagramRoute: ApiSylangDiagramRoute,
  ApiSylangSymbolDetailsRoute: ApiSylangSymbolDetailsRoute,
  ApiSylangSymbolsRoute: ApiSylangSymbolsRoute,
  ApiSylangVariantMatrixRoute: ApiSylangVariantMatrixRoute,
  ApiWorkspacesCloneRoute: ApiWorkspacesCloneRoute,
  ApiWorkspacesCreateRoute: ApiWorkspacesCreateRoute,
  ApiWorkspacesListRoute: ApiWorkspacesListRoute,
  ApiWorkspacesOpenRoute: ApiWorkspacesOpenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
